#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
nohup $OPENSHIFT_REPO_DIR/webapp/opinoid.py --dbhost=$OPENSHIFT_NOSQL_DB_HOST --dbport=$OPENSHIFT_NOSQL_DB_PORT --dbuser=$OPENSHIFT_NOSQL_DB_USERNAME --dbpass=$OPENSHIFT_NOSQL_DB_PASSWORD --log_to_stderr > $OPENSHIFT_LOG_DIR/server.log 2>&1 &